export const COURSES = [
  {
    value: "santacruz_703",
    label: "70.3 Santa Cruz",
    emoji: "🇺🇸",
    url: "/courses/IM_Santa_Cruz_70.3.json",
    origin: "https://www.strava.com/routes/2474490",
  },
  {
    value: "stgeorge_703",
    label: "70.3 St. George",
    emoji: "🇺🇸",
    url: "/courses/IM_St_George_70.3.json",
    origin: "https://www.strava.com/routes/2025697"
  },
  {
    value: "texas_703",
    label: "70.3 Texas",
    emoji: "🇺🇸",
    url: "/courses/IM_Texas_70.3.json",
    origin: "https://www.strava.com/routes/2021621",
  },
  {
    value: "haleakala_kom",
    label: "KOM: Haleakala",
    emoji: "🇺🇸",
    url: "/courses/Haleakala_Climb.json",
    origin: "https://www.strava.com/segments/haleakala-%22world-s-longest-paved-climb%22-638944",
  },
  {
    value: "oceanside_703",
    label: "70.3 Oceanside",
    emoji: "🇺🇸",
    url: "/courses/IM_Oceanside_70.3.json",
    origin: "https://ridewithgps.com/routes/19028235",
  },
  {
    value: "indian_wells_703",
    label: "70.3 Indian Wells",
    emoji: "🇺🇸",
    url: "/courses/IM_Indian_Wells_70.3.json",
    origin: "https://ridewithgps.com/routes/31516727?lang=en",
  },
  {
    value: "taupo_703",
    label: "70.3 Taupo",
    emoji: "🇳🇿",
    url: "/courses/IM_Taupo_70.3.json",
    origin: "https://www.strava.com/routes/2800825",
  },
  {
    value: "chattanooga_703",
    label: "70.3 Chattanooga",
    emoji: "🇺🇸",
    url: "/courses/IM_Chattanooga_70.3.json",
    origin: "https://ridewithgps.com/routes/6491948?lang=en"
  },
  {
    value: "florida_703",
    label: "70.3 Florida",
    emoji: "🇺🇸",
    url: "/courses/IM_Florida_70.3.json",
    origin: "https://www.strava.com/routes/7416785",
  },
  {
    value: "hawaii_703",
    label: "70.3 Hawaii",
    emoji: "🇺🇸",
    url: "/courses/IM_Hawaii_70.3.json",
    origin: "https://www.strava.com/routes/2060690",
  },
  {
    value: "morro_bay_703",
    label: "70.3 Morro Bay",
    emoji: "🇺🇸",
    url: "/courses/IM_Morro_Bay_70.3.json",
    origin: "https://ridewithgps.com/routes/42364410",
  },
  {
    value: "boulder_703",
    label: "70.3 Boulder",
    emoji: "🇺🇸",
    url: "/courses/IM_Boulder_70.3.json",
    origin: "https://ridewithgps.com/routes/6876299",
  },
  {
    value: "des_moines_703",
    label: "70.3 Des Moines",
    emoji: "🇺🇸",
    url: "/courses/IM_Des_Moines_70.3.json",
    origin: "https://ridewithgps.com/routes/31390609",
  },
  {
    value: "eagleman_703",
    label: "70.3 Eagleman",
    emoji: "🇺🇸",
    url: "/courses/IM_Eagleman_70.3.json",
    origin: "https://ridewithgps.com/routes/27117567",
  },
  {
    value: "couer_dalene_703",
    label: "70.3 Couer D'Alene",
    emoji: "🇺🇸",
    url: "/courses/IM_Couer_D'Alene_70.3.json",
    origin: "https://ridewithgps.com/routes/12153451",
  },
  {
    value: "happy_valley_703",
    label: "70.3 Happy Valley",
    emoji: "🇺🇸",
    url: "/courses/IM_Happy_Valley_70.3.json",
    origin: "https://ridewithgps.com/routes/41778618",
  },
  {
    value: "augusta_703",
    label: "70.3 Augusta",
    emoji: "🇺🇸",
    url: "/courses/IM_Augusta_70.3.json",
    origin: "https://www.strava.com/routes/3657738",
  },
  {
    value: "maine_703",
    label: "70.3 Maine",
    emoji: "🇺🇸",
    url: "/courses/IM_Maine_70.3.json",
    origin: "https://ridewithgps.com/routes/39903147",
  },
  {
    value: "north_carolina_703",
    label: "70.3 North Carolina",
    emoji: "🇺🇸",
    url: "/courses/IM_North_Carolina_70.3.json",
    origin: "https://www.strava.com/routes/6358077",
  },
  {
    value: "waco_703",
    label: "70.3 Waco",
    emoji: "🇺🇸",
    url: "/courses/IM_Waco_70.3.json",
    origin: "https://www.strava.com/routes/21984028"
  },
  {
    value: "mont_tremblant_703",
    label: "70.3 Mont Tremblant",
    emoji: "🇨🇦",
    url: "/courses/IM_Mont_Tremblant_70.3.json",
    origin: "https://ridewithgps.com/routes/3797415",
  },
  // {
  //   value: "nice_703",
  //   label: "Nice 70.3",
  //   emoji: "🇫🇷",
  //   origin: "https://ridewithgps.com/routes/28349391",
  // },
  {
    value: "lake_placid_im",
    label: "Ironman Lake Placid",
    emoji: "🇺🇸",
    url: "/courses/IM_Lake_Placid_140.6.json",
    origin: "https://www.strava.com/routes/2346273"
  },
  {
    value: "kona_im",
    label: "Ironman World Championships (Kona)",
    emoji: "🤙",
    url: "/courses/IM_Kona_140.6.json",
    origin: "https://ridewithgps.com/routes/1969147?lang=en"
  }
].sort((a, b) => a.label < b.label ? -1 : 1);
